### ISSUE TITLE
haddock3 table not showing up in the analysis report

### ISSUE THREAD

**Issue by mgiulini** [i-VRESSE/haddock3-analysis-components#14]
the haddock3 report.html is not showing the cluster table anymore. only scatter and box plots are present at the moment.

Attached capri_ss.tsv and capri_clt.tsv files
[Archive.zip](https://github.com/user-attachments/files/15510483/Archive.zip)

**Comment by sverhoeven** [comment]
Can you also give the report.html?

**Comment by mgiulini** [comment]
[report.html.zip](https://github.com/user-attachments/files/15510698/report.html.zip)
here it is!

**Comment by sverhoeven** [comment]
I published a new version of the package and me the report.html now renders the table. 

Could you try it?

**Comment by mgiulini** [comment]
report is there, the download works but the viewer is not displaying the models
